kind: Service
apiVersion: v1
metadata:
  name: account-service
  namespace: ${TARGET_NAMESPACE}
  labels:
    version: ${TARGET_VERSION}
spec:
  selector:
    app: account-service
    version: ${TARGET_VERSION}
  ports:
  - port: 80
    targetPort: 80
  