kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: ${TARGET_NAMESPACE}
  labels:
    version: ${TARGET_VERSION}
spec:
  selector:
    app: gateway
    version: ${TARGET_VERSION}
  ports:
  - name: management
    port: 4000
    targetPort: 4000
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
