kind: Service
apiVersion: v1
metadata:
  name: monitoring
  namespace: ${TARGET_NAMESPACE}
  labels:
    version: ${TARGET_VERSION}
spec:
  selector:
    app: monitoring
    version: ${TARGET_VERSION}
  ports:
  - port: 8080
    targetPort: 8080
  