kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: ${TARGET_NAMESPACE}
  labels:
    version: ${TARGET_VERSION}
spec:
  selector:
    app: rabbitmq
    version: ${TARGET_VERSION}
  ports:
  - name: management
    port: 5672
    targetPort: 5672
  - name: dashboard
    port: 15672
    targetPort: 15672
  - name: epmd
    port: 4369
    targetPort: 4369
