kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: ${TARGET_NAMESPACE}
  labels:
    version: ${TARGET_VERSION}
spec:
  selector:
    app: rabbitmq
    version: ${TARGET_VERSION}
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: node
    port: 5672
    targetPort: node
  - name: dist
    port: 25672
    targetPort: dist
  - name: management
    port: 15672
    targetPort: management
  type: ClusterIP