kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: ${TARGET_NAMESPACE}
  labels:
    version: ${TARGET_VERSION}
spec:
  selector:
    app: registry
    version: ${TARGET_VERSION}
  ports:
  - port: 8761
    targetPort: 8761
  