apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piggy-metrics-canary-ingress
  namespace: piggy 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-cookie: "canary"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gateway-canary
          servicePort: 80