apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piggy-metrics-ingress
  namespace: piggy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-cookie: "canary"
spec:
  rules:
  - host: demo-aks-ingress.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 80
        path: /
      - backend:
          serviceName: auth-service
          servicePort: 80
        path: /uaa/.*
      - backend:
          serviceName: account-service
          servicePort: 80
        path: /accounts/.*