apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service-${TARGET_VERSION}
  namespace: ${TARGET_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: account-service

  template:
    metadata:
      labels:
        app: account-service
        version: ${TARGET_VERSION}

    spec:
      containers:
      - name: ${ACCOUNT_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${ACCOUNT_IMAGE_NAME}:${IMAGE_TAG}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_PASSWORD
            value: admin
        ports:
        - containerPort: 6000
      imagePullSecrets:
      - name: "${ACR_SECRET_NAME}"
