apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-${TARGET_VERSION}
  namespace: ${TARGET_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: config

  template:
    metadata:
      labels:
        app: config
        version: ${TARGET_VERSION}

    spec:
      containers:
      - name: ${CONFIG_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${CONFIG_IMAGE_NAME}:${IMAGE_TAG}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_PASSWORD
            value: admin
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: "${ACR_SECRET_NAME}"
  