apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-service-${TARGET_VERSION}
  namespace: ${TARGET_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: statistics-service

  template:
    metadata:
      labels:
        app: statistics-service
        version: ${TARGET_VERSION}

    spec:
      containers:
      - name: ${STATISTICS_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${STATISTICS_IMAGE_NAME}:${IMAGE_TAG}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_PASSWORD
            value: admin
        ports:
          - containerPort: 7000
      imagePullSecrets:
      - name: "${ACR_SECRET_NAME}"
  